#!/bin/bash


REGISTRY=""

VOLUMES="-v $HOME/.aws:/root/.aws \
        -v ${PWD}:/share \
        -v $HOME/.kube:/root/.kube \
        -v /var/run/docker.sock:/var/run/docker.sock"

opt_count=0

while getopts "c" arg > /dev/null 2>&1; do
  case "${arg}" in
    c)
      opt_count=$((opt_count + 1))
      MY_CONTAINER_ID=`cat /proc/self/cgroup |awk -F '/' '$2 = "docker" && NR == 1 {print $NF }'`
      VOLUMES="--volumes-from ${MY_CONTAINER_ID} -w ${CONTAINER_PATH}"
      ;;
    *)
      ;;
  esac
done

# get rid of options passed the to script and not passed onto the container
shift $opt_count

docker run -ti --rm \
  ${VOLUMES} \
  ${REGISTRY}gantry $@
